version: "3"

services:
  #   front-server:
  #     container_name: front-server
  #     restart: always
  #     build: .
  #     ports:
  #       - "4201:4200"
  #     depends_on:
  #       - back-server
  backend-server:
    container_name: backend-server
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - "./back/src/:/usr/src/app/src"
    environment:
      - PORT=3001
    #   - DATABASE_CONFIG=sqlite::memory:
#         - DYNAMODB_ENDPOINT="http://localhost:8042"
#     depends_on:
#         - database
#   database:
#     container_name: database
#     image: amazon/dynamodb-local
#     hostname: dynamodb-local
#     container_name: dynamodb-local
#     ports:
#         - "8042:8000"%
